import type { User } from "@supabase/supabase-js";
import type { Investigation, AppNotification, Evidence, TimelineEvent, Contradiction, Unknown } from "./types";
import { requireSupabase, supabase } from "./supabase";

export interface Session { id: string; name: string; email: string; role: string; workspace: string; createdAt: string; }
const asSession = (user: User, profile?: Record<string, unknown> | null): Session => ({ id: user.id, name: String(profile?.display_name || user.user_metadata?.name || user.email?.split("@")[0] || "Investigator"), email: user.email || "", role: String(profile?.role || "Investigator"), workspace: String(profile?.workspace || ""), createdAt: user.created_at });
async function currentUser() { const { data, error } = await supabase.auth.getUser(); if (error || !data.user) return null; const { data: profile } = await supabase.from("profiles").select("display_name,role,workspace").eq("id", data.user.id).maybeSingle(); return asSession(data.user, profile); }
export const authService = {
  async current() { return currentUser(); },
  async signIn(email: string, password: string) { const { data, error } = await requireSupabase().auth.signInWithPassword({ email, password }); if (error || !data.user) throw new Error(error?.message || "Unable to sign in."); return asSession(data.user); },
  async signUp(name: string, email: string, password: string) { const { data, error } = await requireSupabase().auth.signUp({ email, password, options: { data: { name } } }); if (error || !data.user) throw new Error(error?.message || "Unable to create account."); return asSession(data.user); },
  async resetPassword(email: string) { const { error } = await requireSupabase().auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/sign-in` }); if (error) throw new Error(error.message); },
  async signOut() { const { error } = await requireSupabase().auth.signOut(); if (error) throw new Error(error.message); },
  async updateProfile(patch: Partial<Session>) { const user = (await requireSupabase().auth.getUser()).data.user; if (!user) return; const { error } = await requireSupabase().from("profiles").upsert({ id: user.id, display_name: patch.name, role: patch.role, workspace: patch.workspace }); if (error) throw new Error(error.message); },
};
const fmt = (v: string | null) => v ? new Date(v).toLocaleDateString("en-US", { month: "short", day: "2-digit", year: "numeric" }) : "—";
const mapEvidence = (e: any): Evidence => ({ id: e.id, filename: e.filename, type: e.mime_type?.startsWith("image/") ? "image" : e.mime_type === "application/pdf" ? "pdf" : e.mime_type?.startsWith("audio/") ? "audio" : e.mime_type?.startsWith("text/") ? "text" : "document", size: `${Math.max(1, Math.round((e.size_bytes || 0) / 1024))} KB`, uploadedAt: fmt(e.created_at), relevantTime: e.relevant_time ? fmt(e.relevant_time) : "Unknown", status: e.status, confidence: e.status === "verified" ? "high" : e.status === "uncertain" ? "low" : "medium", sourceId: e.id, observations: [], relatedEvents: [], relatedContradictions: [], notes: e.notes || undefined });
const mapInvestigation = (i: any): Investigation => { const evidence = (i.evidence || []).map(mapEvidence); const events: TimelineEvent[] = (i.timeline_events || []).map((e: any) => ({ id: e.id, time: e.event_time ? new Date(e.event_time).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "Unknown", date: fmt(e.event_time), title: e.title, description: e.description, confidence: e.confidence, sources: e.evidence_ids || [], label: e.basis === "observed" ? "evidence-backed" : e.basis === "inferred" ? "inferred" : e.basis === "ai-observation" ? "ai-observation" : "uncertain" })); const contradictions: Contradiction[] = (i.contradictions || []).map((c: any) => ({ id: c.id, code: c.id.slice(0, 6).toUpperCase(), title: c.title, sourceA: { evidenceId: c.evidence_ids?.[0] || "", label: "Claim A", time: "" }, sourceB: { evidenceId: c.evidence_ids?.[1] || "", label: "Claim B", time: "" }, issue: c.title, detail: c.description, confidence: c.confidence, status: c.status, eventIds: [], notes: c.resolution_needed })); const unknowns: Unknown[] = (i.unknowns || []).map((u: any) => ({ id: u.id, title: u.title, description: u.description, window: "Unresolved", potentialEvidence: u.recommended_evidence || [], status: u.status, severity: u.severity })); return { id: i.id, slug: i.slug, name: i.name, status: i.status === "processing" ? "analyzing" : i.status, createdAt: fmt(i.created_at), updatedAt: fmt(i.updated_at), updatedLabel: "recently", incidentDate: fmt(i.incident_date), description: i.description, evidenceCount: evidence.length, eventCount: events.length, contradictionCount: contradictions.length, unknownCount: unknowns.length, confidence: i.confidence || 0, coverage: { verified: evidence.filter((e: Evidence) => e.status === "verified").length, uncertain: evidence.filter((e: Evidence) => e.status === "uncertain").length, missing: unknowns.length }, timelineConfidence: i.confidence || 0, requiresReview: contradictions.filter((c: Contradiction) => c.status !== "resolved").length, evidence, events, contradictions, unknowns, activity: [] }; };
async function loadInvestigation(query: any) { const { data, error } = await query; if (error) throw new Error(error.message); return mapInvestigation(data); }
export const investigationService = {
  async list() { const { data, error } = await requireSupabase().from("investigations").select("*, evidence(*), timeline_events(*), contradictions(*), unknowns(*)").order("updated_at", { ascending: false }); if (error) throw new Error(error.message); return (data || []).map(mapInvestigation); },
  async get(id: string) { const q = requireSupabase().from("investigations").select("*, evidence(*), timeline_events(*), contradictions(*), unknowns(*)").or(`id.eq.${id},slug.eq.${id}`).maybeSingle(); try { return await loadInvestigation(q); } catch { return undefined; } },
  async create(input: { name: string; description: string; incidentDate: string; files?: File[] }) { const client = requireSupabase(); const user = (await client.auth.getUser()).data.user; if (!user) throw new Error("Your session has expired. Please sign in again."); const slug = `${input.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "investigation"}-${Date.now().toString(36)}`; const { data: row, error } = await client.from("investigations").insert({ owner_id: user.id, name: input.name, slug, description: input.description, incident_date: input.incidentDate || null, status: "uploading" }).select().single(); if (error) throw new Error(error.message); for (const file of input.files || []) await this.upload(row.id, file); if ((input.files || []).length) { const { error: updateError } = await client.from("investigations").update({ status: "ready" }).eq("id", row.id); if (updateError) throw new Error(updateError.message); } return mapInvestigation({ ...row, evidence: [], timeline_events: [], contradictions: [], unknowns: [] }); },
  async upload(investigationId: string, file: File) { const client = requireSupabase(); const user = (await client.auth.getUser()).data.user; if (!user) throw new Error("Your session has expired."); const evidenceId = crypto.randomUUID(); const path = `${user.id}/${investigationId}/${evidenceId}/${file.name.replace(/[^a-zA-Z0-9._-]/g, "_")}`; const { error: uploadError } = await client.storage.from("evidence").upload(path, file, { contentType: file.type, upsert: false }); if (uploadError) throw new Error(uploadError.message); const { data, error } = await client.from("evidence").insert({ id: evidenceId, investigation_id: investigationId, uploaded_by: user.id, filename: file.name, mime_type: file.type || "application/octet-stream", size_bytes: file.size, storage_path: path, status: "ready" }).select().single(); if (error) { await client.storage.from("evidence").remove([path]); throw new Error(error.message); } return mapEvidence(data); },
  async startAnalysis(investigationId: string) { const client = requireSupabase(); const user = (await client.auth.getUser()).data.user; if (!user) throw new Error("Your session has expired."); const { data, error } = await client.from("analysis_runs").insert({ investigation_id: investigationId, requested_by: user.id }).select().single(); if (error) throw new Error(error.message); await client.from("investigations").update({ status: "processing" }).eq("id", investigationId); const { error: fnError } = await client.functions.invoke("analyze-evidence", { body: { investigationId, runId: data.id } }); if (fnError) throw new Error("Analysis could not be started. No evidence was lost."); return data; },
  async analysisStatus(investigationId: string) { const { data, error } = await requireSupabase().from("analysis_runs").select("status,stage,progress,error_message").eq("investigation_id", investigationId).order("created_at", { ascending: false }).limit(1).maybeSingle(); if (error) throw new Error(error.message); return data; },
};
export const notificationService = { async list() { const { data, error } = await requireSupabase().from("notifications").select("*").order("created_at", { ascending: false }); if (error) throw new Error(error.message); return (data || []).map((n: any): AppNotification => ({ id: n.id, title: n.title, body: n.body, time: fmt(n.created_at), read: n.read, kind: n.kind })); } };
export const ANALYSIS_STAGES = [{ n: "01", label: "Ingesting evidence" }, { n: "02", label: "Normalizing timestamps" }, { n: "03", label: "Correlating sources" }, { n: "04", label: "Reconstructing events" }, { n: "05", label: "Searching for contradictions" }, { n: "06", label: "Identifying unknown evidence" }, { n: "07", label: "Assembling timeline" }, { n: "08", label: "Investigation ready" }];
