import { useEffect, useState } from "react";
import { motion } from "motion/react";
import { Check, Loader2 } from "lucide-react";
import { ANALYSIS_STAGES, investigationService } from "../../lib/services";
import { cn } from "../../lib/cn";
export function AnalysisProgress({ investigationId, onComplete }: { investigationId: string; onComplete: () => void }) {
  const [progress, setProgress] = useState(0); const [stage, setStage] = useState(0); const [error, setError] = useState("");
  useEffect(() => { let active = true; const check = async () => { try { const run = await investigationService.analysisStatus(investigationId); if (!active || !run) return; setProgress(run.progress || 0); setStage(Math.min(ANALYSIS_STAGES.length - 1, Math.floor((run.progress || 0) / 100 * ANALYSIS_STAGES.length))); if (run.status === "complete") onComplete(); if (run.status === "failed") setError(run.error_message || "Analysis could not be completed. No evidence was lost."); } catch (e) { if (active) setError(e instanceof Error ? e.message : "Unable to read analysis status."); } }; check(); const timer = window.setInterval(check, 1800); return () => { active = false; window.clearInterval(timer); }; }, [investigationId, onComplete]);
  return <div className="mx-auto max-w-3xl"><div className="mb-8 text-center"><p className="font-mono text-xs uppercase tracking-[0.2em] text-accent">Reconstructing incident</p><h2 className="mt-2 font-display text-2xl font-bold tracking-tight text-fg">Correlating evidence across sources</h2><p className="mt-1 text-sm text-fg-dim">The workspace reflects the current backend analysis state.</p>{error&&<p className="mt-4 rounded border border-crimson/30 bg-crimson/10 p-3 text-sm text-crimson">{error}</p>}</div><div className="mb-6"><div className="mb-1.5 flex justify-between text-xs"><span className="text-fg-muted">Overall progress</span><span className="font-mono tabular text-accent">{progress}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-surface-3"><motion.div className="h-full rounded-full bg-accent" animate={{ width: `${progress}%` }} transition={{ duration: 0.6 }}/></div></div><div className="grid gap-1.5 sm:grid-cols-2">{ANALYSIS_STAGES.map((s,i)=>{const done=i<stage;const active=i===stage;return <motion.div key={s.n} animate={{opacity:i>stage+1?.4:1}} className={cn("flex items-center gap-3 rounded-sm border px-3 py-2.5",active?"border-accent/40 bg-accent/5":done?"border-line bg-surface":"border-line/60 bg-surface/50")}><span className={cn("grid size-6 shrink-0 place-items-center rounded-full text-[11px]",done?"bg-verified/15 text-verified":active?"bg-accent/15 text-accent":"bg-surface-3 text-fg-dim")}>{done?<Check className="size-3.5"/>:active?<Loader2 className="size-3.5 animate-spin"/>:s.n}</span><span className={cn("text-sm",active?"text-fg":done?"text-fg-muted":"text-fg-dim")}>{s.label}</span></motion.div>})}</div></div>;
}
