import { useEffect, useState } from "react";
import { Check, Loader2 } from "lucide-react";
import { ANALYSIS_STAGES } from "../../lib/services";
export function AnalysisProgress({ onComplete }: { onComplete: () => void }) {
 const [stage,setStage]=useState(0);
 useEffect(()=>{if(stage>=ANALYSIS_STAGES.length-1){const t=setTimeout(onComplete,900);return()=>clearTimeout(t)}const t=setTimeout(()=>setStage(s=>s+1),700);return()=>clearTimeout(t)},[stage,onComplete]);
 const pct=Math.round(stage/(ANALYSIS_STAGES.length-1)*100);
 return <div className="mx-auto max-w-3xl"><div className="mb-6 flex items-end justify-between"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">Reconstructing incident</p><h2 className="mt-2 font-display text-2xl font-bold">Correlating multimodal evidence</h2></div><span className="font-mono text-sm tabular text-fg-dim">{pct}%</span></div><div className="mb-6 h-1 overflow-hidden rounded-full bg-surface-3"><div className="h-full bg-accent transition-all duration-500" style={{width:`${pct}%`}}/></div><div className="overflow-hidden rounded-lg border border-line bg-surface">{ANALYSIS_STAGES.map((s,i)=><div key={s.n} className="flex items-center gap-4 border-b border-line px-5 py-4 last:border-0"><div className={`grid size-7 place-items-center rounded-full border ${i<stage?'border-verified/50 bg-verified/10 text-verified':i===stage?'border-accent/50 bg-accent-dim text-accent':'border-line-2 text-fg-faint'}`}>{i<stage?<Check className="size-3.5"/>:i===stage?<Loader2 className="size-3.5 animate-spin"/>:<span className="font-mono text-[10px]">{s.n}</span>}</div><span className={i<=stage?'text-fg':'text-fg-dim'}>{s.label}</span>{i<stage&&<span className="ml-auto font-mono text-[10px] text-verified">complete</span>}</div>)}</div></div>;
}
