import { Clock, FileText, Sparkles, AlertTriangle } from "lucide-react";
import { Drawer } from "../ui/overlays";
import { Badge, Button, ConfidenceTag, EvidenceIcon, Textarea } from "../ui";
import type { Contradiction, Evidence, Investigation } from "../../lib/types";

export function EvidenceInspector({ evidence, investigation, open, onClose, onSelectEvent, onSaveNote }:{evidence:Evidence|null;investigation:Investigation;open:boolean;onClose:()=>void;onSelectEvent?:(id:string)=>void;onSaveNote?:(note:string)=>void}){if(!evidence)return null;return <Drawer open={open} onClose={onClose} title={evidence.filename}><div className="space-y-6"><div><div className="flex items-center gap-3"><EvidenceIcon type={evidence.type}/><div><div className="font-display font-semibold">{evidence.filename}</div><div className="text-xs text-fg-dim">{evidence.size}</div></div><div className="ml-auto"><ConfidenceTag confidence={evidence.confidence}/></div></div></div><div><h4 className="mb-2 font-mono text-[10px] uppercase tracking-wider text-fg-faint">Observed</h4><div className="space-y-2">{evidence.observations.map(x=><div key={x} className="rounded-md border border-line bg-surface p-3 text-sm text-fg-muted">{x}</div>)}</div></div><div><h4 className="mb-2 font-mono text-[10px] uppercase tracking-wider text-fg-faint">Linked events</h4><div className="space-y-2">{evidence.relatedEvents.map(id=>{const e=investigation.events.find(x=>x.id===id);return e?<button onClick={()=>onSelectEvent?.(e.id)} key={e.id} className="flex w-full items-center gap-3 rounded-md border border-line bg-surface p-3 text-left hover:border-accent/40"><Clock className="size-4 text-accent"/><span className="font-mono text-xs">{e.time}</span><span className="truncate text-sm">{e.title}</span></button>:null})}</div></div><div><h4 className="mb-2 font-mono text-[10px] uppercase tracking-wider text-fg-faint">Investigator note</h4><Textarea defaultValue={evidence.notes} placeholder="Record a review note..." onBlur={e=>onSaveNote?.(e.target.value)}/></div></div></Drawer>}

export function ContradictionInspector({ contradiction, open, onClose }:{contradiction:Contradiction|null;open:boolean;onClose:()=>void}){if(!contradiction)return null;return <Drawer open={open} onClose={onClose} title="Contradiction"><div className="space-y-5"><div className="flex items-center gap-2"><AlertTriangle className="size-4 text-crimson"/><Badge tone="crimson">{contradiction.code}</Badge><ConfidenceTag confidence={contradiction.confidence}/></div><div><h3 className="font-display text-lg font-semibold">{contradiction.title}</h3><p className="mt-2 text-sm leading-6 text-fg-dim">{contradiction.detail}</p></div><div className="grid gap-3"><div className="rounded-md border border-line bg-surface p-4"><p className="font-mono text-[10px] uppercase tracking-wider text-fg-faint">Source A</p><p className="mt-2 text-sm">{contradiction.sourceA.label}</p><p className="mt-1 text-xs text-fg-dim">{contradiction.sourceA.claim}</p></div><div className="rounded-md border border-crimson/20 bg-crimson-dim p-4"><p className="font-mono text-[10px] uppercase tracking-wider text-fg-faint">Source B</p><p className="mt-2 text-sm">{contradiction.sourceB.label}</p><p className="mt-1 text-xs text-fg-dim">{contradiction.sourceB.claim}</p></div></div><p className="flex items-center gap-2 text-xs text-fg-dim"><Sparkles className="size-3.5 text-accent"/> AI surfaced this conflict; investigator review is required.</p></div></Drawer>}

export function PreviewDrawer({ title, open, onClose, children }:{title:string;open:boolean;onClose:()=>void;children:React.ReactNode}){return <Drawer title={title} open={open} onClose={onClose}>{children}</Drawer>}
