import { AlertTriangle, ArrowRight, HelpCircle, Plus } from "lucide-react";
import type { Contradiction, Investigation, Unknown } from "../../lib/types";
import { Badge, Button, ConfidenceTag, StatusBadge } from "../ui";

export function ContradictionCard({ contradiction:c, investigation, selected, dimmed, onSelect }:{contradiction:Contradiction;investigation:Investigation;selected?:boolean;dimmed?:boolean;onSelect:()=>void}){return <button onClick={onSelect} className={`w-full rounded-md border p-4 text-left transition ${selected?'border-crimson/50 bg-crimson-dim':'border-line bg-surface hover:border-crimson/30'} ${dimmed?'opacity-45':''}`}><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><AlertTriangle className="size-4 text-crimson"/><span className="font-mono text-xs text-crimson">{c.code}</span></div><StatusBadge status={c.status}/></div><h3 className="mt-3 font-display font-semibold">{c.title}</h3><p className="mt-1 text-sm text-fg-dim">{c.detail}</p><div className="mt-3 flex items-center gap-2"><ConfidenceTag confidence={c.confidence}/><span className="text-xs text-fg-faint">{c.sourceA.label} vs {c.sourceB.label}</span></div></button>}

export function UnknownCard({ unknown:u, selected, onSelect }:{unknown:Unknown;selected?:boolean;onSelect:()=>void}){return <button onClick={onSelect} className={`w-full rounded-md border p-4 text-left transition ${selected?'border-amber/50 bg-amber-dim':'border-line bg-surface hover:border-amber/30'}`}><div className="flex items-center justify-between"><div className="flex items-center gap-2"><HelpCircle className="size-4 text-amber"/><span className="font-mono text-xs uppercase tracking-wider text-amber">Evidence gap</span></div><Badge tone={u.severity==='high'?'crimson':'amber'}>{u.severity}</Badge></div><h3 className="mt-3 font-display font-semibold">{u.title}</h3><p className="mt-1 text-sm text-fg-dim">{u.description}</p><div className="mt-4 flex items-center gap-2 text-xs text-accent">Review candidate evidence <ArrowRight className="size-3"/></div></button>}

export function EmptyAnalysisPanel({ onAdd }:{onAdd:()=>void}){return <div className="rounded-lg border border-dashed border-line-strong bg-surface p-8 text-center"><Plus className="mx-auto size-5 text-fg-dim"/><h3 className="mt-3 font-display font-semibold">More evidence can strengthen this view</h3><p className="mx-auto mt-1 max-w-md text-sm text-fg-dim">Add an artifact and rerun reconstruction to update relationships, contradictions and unknowns.</p><Button className="mt-5" variant="outline" onClick={onAdd}>Add evidence</Button></div>}
