import { useMemo } from "react";
import { motion } from "motion/react";
import type { Investigation } from "../../lib/types";
import { EvidenceIcon } from "../ui";

export function RelationshipMap({ investigation, selectedEvidence, selectedEvent, selectedContradiction, onSelectEvidence, onSelectEvent }:{investigation:Investigation;selectedEvidence:string|null;selectedEvent:string|null;selectedContradiction:string|null;onSelectEvidence:(id:string)=>void;onSelectEvent:(id:string)=>void}){
 const evidence=investigation.evidence.slice(0,6),events=investigation.events.slice(0,7),contradictions=investigation.contradictions.slice(0,5);
 const edges=useMemo(()=>events.flatMap((e,i)=>e.sources.slice(0,2).map((s,j)=>({a:s.evidenceId,b:e.id,k:`${i}-${j}`}))),[events]);
 return <div className="overflow-auto rounded-lg border border-line bg-surface grid-texture"><svg viewBox="0 0 900 520" className="min-w-[760px] w-full"><g>{edges.map(ed=>{const a=Math.max(0,evidence.findIndex(x=>x.id===ed.a));const b=Math.max(0,events.findIndex(x=>x.id===ed.b));const y1=55+a*72,y2=55+b*58;return <line key={ed.k} x1="190" y1={y1} x2="440" y2={y2} stroke={selectedEvidence===ed.a||selectedEvent===ed.b?'#56a8f5':'#35424f'} strokeWidth={selectedEvidence===ed.a||selectedEvent===ed.b?2:1}/>})}</g><g>{evidence.map((e,i)=><motion.g key={e.id} whileHover={{scale:1.03}} onClick={()=>onSelectEvidence(e.id)} className="cursor-pointer"><rect x="30" y={28+i*72} width="160" height="52" rx="6" fill="#1e2733" stroke={selectedEvidence===e.id?'#56a8f5':'#35424f'}/><foreignObject x="42" y={40+i*72} width="140" height="30"><div className="flex items-center gap-2 text-[11px] text-[#aab6c3]"><EvidenceIcon type={e.type}/><span className="truncate">{e.filename}</span></div></foreignObject></motion.g>)}</g><g>{events.map((e,i)=><g key={e.id}><circle cx="440" cy={55+i*58} r="7" fill={e.confidence==='high'?'#34d399':e.confidence==='medium'?'#fbbf24':'#f05252'}/><text x="458" y={49+i*58} fill="#eef2f7" fontSize="12" fontFamily="Space Grotesk">{e.time} · {e.title.slice(0,30)}</text></g>)}</g><g>{contradictions.map((c,i)=><g key={c.id}><rect x="650" y={30+i*90} width="215" height="62" rx="6" fill="#28191c" stroke="#f05252" strokeOpacity=".4"/><text x="665" y={55+i*90} fill="#f05252" fontSize="11" fontFamily="JetBrains Mono">{c.code}</text><text x="665" y={74+i*90} fill="#d8c6c7" fontSize="10" fontFamily="Space Grotesk">{c.title.slice(0,27)}</text></g>)}</g></svg></div>;
}
