import { useEffect,useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, AlertTriangle, Clock3, FileText, HelpCircle, Plus } from "lucide-react";
import { investigationService } from "../../lib/services";
import type { Investigation } from "../../lib/types";
import { Page } from "../../components/shell/Page";
import { Badge, Button, ConfidenceRing } from "../../components/ui";

export default function Dashboard(){const [items,setItems]=useState<Investigation[]>([]);useEffect(()=>{investigationService.list().then(setItems)},[]);const focus=items[0];return <Page eyebrow="Workspace" title="Investigation dashboard" subtitle="A compact view of active cases, evidence coverage and review pressure."><div className="grid gap-4 md:grid-cols-4">{[[FileText,"Evidence",focus?.evidenceCount??0,"text-accent"],[Clock3,"Events",focus?.eventCount??0,"text-accent-3"],[AlertTriangle,"Contradictions",focus?.contradictionCount??0,"text-crimson"],[HelpCircle,"Unknowns",focus?.unknownCount??0,"text-amber"]].map(([I,l,v,c])=><div key={l as string} className="rounded-md border border-line bg-surface p-5"><I className={`size-4 ${c}`}/><div className="mt-4 font-display text-3xl font-bold">{v as number}</div><div className="mt-1 text-xs text-fg-dim">{l as string}</div></div>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-lg border border-line bg-surface"><div className="flex items-center justify-between border-b border-line p-5"><div><p className="font-mono text-[10px] uppercase tracking-wider text-fg-faint">Active investigation</p><h2 className="mt-1 font-display text-lg font-semibold">{focus?.name??"No active case"}</h2></div>{focus&&<Link to={`/app/investigations/${focus.slug}`}><Button variant="outline" size="sm" icon={<ArrowRight className="size-3.5"/>}>Open</Button></Link>}</div><div className="grid gap-6 p-6 sm:grid-cols-[auto_1fr]"><ConfidenceRing value={focus?.confidence??0} size={112}/><div className="space-y-3 text-sm text-fg-dim"><div className="flex justify-between"><span>Evidence coverage</span><span className="text-fg">{focus?.coverage.verified??0} verified · {focus?.coverage.uncertain??0} uncertain</span></div><div className="flex justify-between"><span>Timeline confidence</span><span className="text-fg">{focus?.timelineConfidence??0}%</span></div><div className="flex justify-between"><span>Review queue</span><Badge tone={focus?.requiresReview?'crimson':'verified'}>{focus?.requiresReview??0} items</Badge></div></div></div></section><section className="rounded-lg border border-line bg-bg-2 p-6"><p className="font-mono text-[10px] uppercase tracking-wider text-fg-faint">Next action</p><h2 className="mt-2 font-display text-xl font-semibold">Bring the fragments together.</h2><p className="mt-2 text-sm leading-6 text-fg-dim">Start a case, add the source material, then run reconstruction to generate the timeline.</p><Link to="/app/investigations/new"><Button className="mt-5" icon={<Plus className="size-4"/>}>New investigation</Button></Link></section></div></Page>}
