import { useEffect,useState } from "react";
import { useParams } from "react-router-dom";
import { AlertTriangle, Network } from "lucide-react";
import { investigationService } from "../../lib/services";
import type { Investigation } from "../../lib/types";
import { Page } from "../../components/shell/Page";
import { Badge, Tabs } from "../../components/ui";
import { RelationshipMap } from "../../components/investigation/RelationshipMap";
import { Timeline } from "../../components/investigation/Timeline";
import { EvidenceInspector, ContradictionInspector } from "../../components/investigation/drawers";
import { ContradictionCard, UnknownCard } from "../../components/investigation/panels";
export default function InvestigationWorkspace(){const {id="northbridge"}=useParams();const [inv,setInv]=useState<Investigation>();const [tab,setTab]=useState("weave");const [event,setEvent]=useState<string|null>(null);const [ev,setEv]=useState<string|null>(null);const [co,setCo]=useState<string|null>(null);useEffect(()=>{investigationService.get(id).then(setInv)},[id]);if(!inv)return <Page eyebrow="Investigation" title="Loading case…"/>;const selectedEvidence=inv.evidence.find(x=>x.id===ev)??null;const selectedContradiction=inv.contradictions.find(x=>x.id===co)??null;return <Page eyebrow="Investigation" title={inv.name} subtitle={inv.description} actions={<Badge tone={inv.status==='complete'?'verified':'amber'}>{inv.status}</Badge>}><Tabs value={tab} onChange={setTab} items={[{value:"weave",label:"Relationship weave"},{value:"timeline",label:"Timeline"},{value:"conflicts",label:`Conflicts ${inv.contradictionCount}`},{value:"unknowns",label:`Unknowns ${inv.unknownCount}`}]}/><div className="mt-5">{tab==="weave"&&<RelationshipMap investigation={inv} selectedEvidence={ev} selectedEvent={event} selectedContradiction={co} onSelectEvidence={setEv} onSelectEvent={setEvent}/>} {tab==="timeline"&&<Timeline investigation={inv} selectedEvent={event} highlightedEvents={new Set()} onSelectEvent={setEvent}/>} {tab==="conflicts"&&<div className="space-y-3">{inv.contradictions.map(c=><ContradictionCard key={c.id} contradiction={c} investigation={inv} selected={co===c.id} onSelect={()=>setCo(c.id)}/>)}</div>} {tab==="unknowns"&&<div className="space-y-3">{inv.unknowns.map(u=><UnknownCard key={u.id} unknown={u} onSelect={()=>{}}/>)}</div>}</div><EvidenceInspector evidence={selectedEvidence} investigation={inv} open={!!ev} onClose={()=>setEv(null)} onSelectEvent={setEvent}/><ContradictionInspector contradiction={selectedContradiction} open={!!co} onClose={()=>setCo(null)}/></Page>}
