import { BrowserRouter, Routes, Route, Navigate, Link } from "react-router-dom";
import { AppProvider, useApp } from "./store/AppContext";
import { AppLayout } from "./components/shell/AppLayout";
import { Button } from "./components/ui";
import { Logo } from "./components/Logo";
import Landing from "./pages/Landing"; import SignIn from "./pages/auth/SignIn"; import SignUp from "./pages/auth/SignUp"; import ForgotPassword from "./pages/auth/ForgotPassword";
import Dashboard from "./pages/app/Dashboard"; import Investigations from "./pages/app/Investigations"; import NewInvestigationDemoSeed from "./pages/app/NewInvestigationDemoSeed"; import QuickInvestigation from "./pages/app/QuickInvestigation"; import InvestigationWorkspace from "./pages/app/InvestigationWorkspace"; import EvidencePage from "./pages/app/Evidence"; import TimelinePage from "./pages/app/TimelinePage"; import Contradictions from "./pages/app/Contradictions"; import Unknowns from "./pages/app/Unknowns"; import SearchPage from "./pages/app/SearchPage"; import Notifications from "./pages/app/Notifications"; import Profile from "./pages/app/Profile"; import Settings from "./pages/app/Settings";
function NotFound() { return <div className="grid min-h-screen place-items-center px-6 text-center"><div><Logo /><h1 className="mt-6 font-display text-5xl font-extrabold text-fg">404</h1><p className="mt-2 text-fg-dim">This page couldn't be found.</p><Link to="/"><Button variant="primary" className="mt-6">Back to home</Button></Link></div></div>; }
function Protected() { const { session, authReady } = useApp(); if (!authReady) return <div className="grid min-h-screen place-items-center text-fg-dim">Loading workspace…</div>; return session ? <AppLayout /> : <Navigate to="/sign-in" replace />; }
export default function App() { return <BrowserRouter><AppProvider><Routes><Route path="/" element={<Landing />} /><Route path="/sign-in" element={<SignIn />} /><Route path="/sign-up" element={<SignUp />} /><Route path="/forgot-password" element={<ForgotPassword />} /><Route path="/app" element={<Protected />}><Route index element={<Navigate to="/app/dashboard" replace />} /><Route path="dashboard" element={<Dashboard />} /><Route path="investigations" element={<Investigations />} /><Route path="investigations/new" element={<NewInvestigationDemoSeed />} /><Route path="investigations/quick" element={<QuickInvestigation />} /><Route path="investigations/:id" element={<InvestigationWorkspace />} /><Route path="evidence" element={<EvidencePage />} /><Route path="timeline" element={<TimelinePage />} /><Route path="contradictions" element={<Contradictions />} /><Route path="unknowns" element={<Unknowns />} /><Route path="search" element={<SearchPage />} /><Route path="notifications" element={<Notifications />} /><Route path="profile" element={<Profile />} /><Route path="settings" element={<Settings />} /></Route><Route path="*" element={<NotFound />} /></Routes></AppProvider></BrowserRouter>; }
